#!/bin/sh /etc/rc.common
START=70
STOP=10

USE_PROCD=1

PROG=/usr/bin/lora-gateway-bridge

service_triggers()
{
  procd_add_reload_trigger "lora-global"
}

reload_service()
{
  logger "reload lora_gateway_bridge service"
}

start_service()
{
  sed -i "s/client_id=\"\"/client_id=\"$(uci get lora-global.gateway_conf.gateway_ID)\"/g" /etc/lora-gateway-bridge/lora-gateway-bridge.toml

  procd_open_instance

  procd_set_param command $PROG

  procd_set_param respawn

  procd_set_param stdout 1
  procd_set_param stderr 1

  procd_close_instance
}
